-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, SUM(P.PRICE * S.SALES_AMOUNT) AS 'SALES'
FROM OFFLINE_SALE S
    LEFT JOIN PRODUCT P
    ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE